### ISSUE TITLE
Modifying/Removing foreignKey doesn't get applied after running migrations:execute

### ISSUE THREAD

**Issue by saada** [andrefigueira/Schematic#31]
``` yaml
status_job:
    type: varchar(50)
    'null': true
    unsigned: false
    autoIncrement: false
    index: INDEX
    foreignKey:
        table: status_sts
        field: name_sts
        on:
            delete: RESTRICT
            update: RESTRICT
```

I found this SO thread that basically says that you have to have the old foreign key name in order to remove it. The only way I can think of is actually querying the existing database for the old foreign key?
http://stackoverflow.com/questions/838354/mysql-removing-some-foreign-keys
